User.destroy_all

mark = User.new(:email => "mark.kilpatrick.miller@gmail.com", 
  bio: 'surving the QFIN program at JMU',
  password: 'password1', 
  password_confirmation: 'password1', 
  username: 'markmiller21',
  first_name: 'Mark', 
  last_name: 'Miller', 
  year: 'Senior',
  student_status: 'college_student', 
  activities: 'Football, Chess Team, Basketball, and Entrepreneurship', 
  personal_description: 'Highschool athlete turned coder', 
  cell_phone: '2024365781', 
  highschool: 'Salisbury School', 
  college: 'James Madison University',
  major: 'Quantitative Finance', 
  avaliability: 'Afternoons 6 PM - 9 PM',
  philanthropy_percent: 5, 
  phone_call_price:  15.00,
  meeting_price:  20.00, 
  video_price:  25.00, 
  venmo: 'markmiller21',
  philanthropy: "JMU: Madison Investment Fund",
  accept_phone_call: true,
  accept_video_call: true,
  accept_meeting: true
)
mark.save



magge = User.new(
  bio: 'surving the QFIN program at JMU',
  password: 'password1', 
  password_confirmation: 'password1', 
  username: 'markmiller21',
  first_name: 'Mark', 
  last_name: 'Miller', 
  year: 'Senior',
  student_status: 'college_student', 
  activities: 'Football, Chess Team, Basketball, and Entrepreneurship', 
  personal_description: 'Highschool athlete turned coder', 
  cell_phone: '2024365781', 
  highschool: 'Salisbury School', 
  college: 'James Madison University',
  major: 'Quantitative Finance', 
  avaliability: 'Afternoons 6 PM - 9 PM',
  philanthropy_percent: 5, 
  phone_call_price:  15.00,
  meeting_price:  20.00, 
  video_price:  25.00, 
  venmo: 'markmiller21',
  philanthropy: "JMU: Madison Investment Fund",
  accept_phone_call: true,
  accept_video_call: true,
  accept_meeting: true
)

ryan = User.new(email: "ryan@georgetown.edu", 
  bio: 'Georgetown advice, financial consulting',
  password: 'password1', 
  password_confirmation: 'password1',
  username: 'ryanmerlini13',
  year: 'Freshman', 
  first_name: 'Ryan', 
  last_name: 'Merlini', 
  student_status: 'college_student', 
  activities: 'Entrepreneurship, writing, cooking, traveling, growing my', 
  personal_description: 'Would love to chat about Georgetown',
  cell_phone: '2024365781', 
  college: 'Georgetown',
  highschool: 'Upper Dublin',
  major: 'Economics', 
  phone_call_price: 15.00,
  meeting_price: 12.50, 
  video_price: 10.00, 
  philanthropy: "Georgetown: The 1789 Scholarship Imperative",
  accept_phone_call: true,
  accept_video_call: true,
  accept_meeting: true
)
ryan.save

michael = User.new (
  bio: 'Athletics at ` University',
  password: 'password1', 
  password_confirmation: 'password1', 
  username: 'michael33miller',
  first_name: 'Michael', 
  last_name: 'Miller', 
  year: 'Senior',
  student_status: 'college_student', 
  activities: 'Lacrosse, Chess, Finance, Ecoomics, Fraternity, Student Government', 
  personal_description: 'Would love to talk brown and college lacrosse', 
  cell_phone: '2024365781', 
  highschool: 'Salisbury School', 
  college: 'James Madison University',
  major: 'Quantitative Finance', 
  avaliability: 'Sunday afternoons after football',
  philanthropy_percent: 25, 
  phone_call_price:  30.00,
  meeting_price:  33.33, 
  video_price:  35.00, 
  venmo: 'markmiller21',
  philanthropy: "Brown: Brown University Sustainable Investment Fund",
  accept_phone_call: true,
  accept_video_call: true,
  accept_meeting: true
)

song = User.new(:email => "terrorgeek@gmail.com", 
  bio: 'Advice on CS program',
  password: 'password1', 
  password_confirmation: 'password1', 
  username: 'songyu',
  year: 'Sophomore', 
  first_name: 'Yu', 
  last_name: 'Song', 
  student_status: 'college_student', 
  activities: 'Football, Chess Team, Basketball, and Entrepreneurship', 
  personal_description: 'Do you love ruby as much as me?', 
  cell_phone: '2024365782', 
  highschool: 'Salisbury School', 
  college: 'University of Virginia',
  major: 'Computer Science', 
  phone_call_price: 25.00,
  meeting_price: 20.00, 
  video_price: 15.00, 
  venmo: 'yuSong', 
  resume_path: '' , 
  common_essay_path: '', 
  college_essay_path: ''
)
# song.avatar_path = File.open(File.expand_path('../fixtures/song_knock.png', __FILE__))
song.save

yahya = User.new(:email => "yahya@georgetown.edu", 
  bio: 'Entrepreneurship advice',
  password: 'password1', 
  password_confirmation: 'password1', 
  username: 'yahyaasfor42',
  year: 'Junior', 
  first_name: 'Yahya', 
  last_name: 'Asfoor', 
  student_status: 'college_student', 
  activities: 'Football, Chess Team, Basketball, and Entrepreneurship', 
  personal_description: 'Entrepreneurship is my passion', 
  philanthropy_percent: 21.12, 
  cell_phone: '2024365780', 
  highschool: 'Salisbury School',
  college: 'George Washington University',
  major: 'Finance', 
  phone_call_price: 25.00,
  meeting_price: 20.00, 
  video_price: 15.00, 
  venmo: 'yayaya', 
  resume_path: '' , 
  common_essay_path: '', 
  college_essay_path: ''
)
# yahya.avatar_path = File.open(File.expand_path('../fixtures/yahya_knock.png', __FILE__))
yahya.save


 ['Harvard: The Harvard Campaign', 'Stanford: The Stanford Fund', 'Georgetown: The 1789 Scholarship Imperative', 'Princeton: Annual Giving', 'Penn: The Penn Fund', 'Yale: Parents Annual Fund for Financial Aid', 'Columbia: General Scholarship', 'JMU: General Scholarship Fund', 'Duke: Alumni Endowed Undergraduate Scholarship', 'UNC: The Dean E. Smith Opening Doors Fund'], 

