class MeetingSetupJob < ApplicationJob
  queue_as :default

  SINCH_API_URL = 'https://callingapi.sinch.com/v1/callouts'
  SINCH_API_KEY = '23caec4e-467a-486a-92f0-43c08b06ad56'
  SINCH_SECRET = 'nvxCFgLcgkuqkHxFqwXJEg=='
  SINCH_CALL_METHOD = 'conferenceCallout'

  #params:
  # 1, person1's phone, callee
  # 2, person2's phone, caller
  # 3, call's id(This is not the sinch's call id, it's the DB's call id) and identity, e.g: 34-callee
  def perform(*args)
    conference_id = UUID.generate
    send_request conference_id, args[0], "#{args[2]}-callee"
    send_request conference_id, args[1], "#{args[2]}-caller"
  end

  #this method is the actual method that call since REST API to really make the call happens
  #parameter list:
  #1, conference_id is generated by Gem UUID everytime and shared by 2 callers. So that
  #     they can hear each other like in the same room
  #2, The actual phone number that is gonna be called, this is the real phone number.
  #3, this db_call_id is the primary key from 'meetings' table, I want to append '-callee or --caller to
  #    identify which one is the caller or callee, cause the order of who hang up first is unpredicted.'
  def send_request(conference_id, phone_number, db_call_id)
    #for rest_params, just care about those 3 passed params, forget about others for now.
    rest_params = {
        "method" => SINCH_CALL_METHOD,
        "conferenceCallout" =>
            {
                "destination" => {"type" => "number", "endpoint" => phone_number},
                "domain" => "pstn",
                "custom" => db_call_id,
                "locale" => "en-US",
                "greeting" => "Welcome to my conference",
                "conferenceId" => conference_id,
                "enableAce" => false,
                "enableDice" => true
            }
    }
    res = RestClient.post SINCH_API_URL, JSON.generate(rest_params), {content_type: :json, :Authorization => 'Basic MjNjYWVjNGUtNDY3YS00ODZhLTkyZjAtNDNjMDhiMDZhZDU2Om52eENGZ0xjZ2t1cWtIeEZxd1hKRWc9PQ=='}
    #TODO will remove this when we launch
    puts "=======#{res.body}"
    puts "=======#{res.code}"
    res.body
  end
end
